{
  "train_micro_batch_size_per_gpu": 25,
  "zero_optimization": {
    "stage": 2,
    "allgather_partitions": true,
    "reduce_scatter": true,
    "contiguous_gradients": true
  },
  "fp16": {
    "enabled": false
  }
}
